### ISSUE TITLE
Conditional Layers / Tri Layers

### ISSUE THREAD

**Issue by evanjrowley** [jthlim/javelin_steno_script#1]
Are there any examples of something like [ZMK conditional layers](https://zmk.dev/docs/features/conditional-layers) / [QMK tri layers ](https://docs.qmk.fm/features/tri_layer)in javelin script?

**Comment by jthlim** [comment]
https://github.com/jthlim/javelin_steno_script/blob/main/scripts/crkbd/crkbd.javelin-script has a number pad by holding down two keys with the left thumb, and a settings layer using function and symbols key at the same time with the right thumb.

However,  recommend that you use the visual editor instead - the Jarne default layout has this configured using the UI.
