### ISSUE TITLE
One Shot Keys / Sticky Keys

### ISSUE THREAD

**Issue by evanjrowley** [jthlim/javelin_steno_script#2]
Are there any examples of something like [ZMK sticky keys](https://zmk.dev/docs/behaviors/sticky-key) / [QMK one shot keys](https://docs.qmk.fm/one_shot_keys) in javelin script?

**Comment by jthlim** [comment]
Not in any default scripts. This could be done by pressing e.g. shift during press and setting a flag, then using a central press handler that checks that flag to automatically release the shift key.

This will be provided at some stage in the future in the visual editor.
